list = [["ABIA", "ISUIKWUATO", "IMENYI", "AHABA IMEYI SECONDARY SCHOOL - AHABA"],
        ["ABIA", "ISUIKWUATO", "IMENYI", "AMAMOGUDU VILLAGE SQUARE - AMAOGUNDU"],
        ["ABIA", "ISUIK", "UMUANYI / ABSU", "NDIOGURU TOWN SQUARE - AMIYI AHABA"],
        ["ABIA", "IS23333UIK", "EZERE"]


list.each {|t|
	t.each
}